/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace EntropyVestingWallet {
  export type VestingScheduleStruct = {
    totalAmount: BytesLike;
    releasedAmount: BytesLike;
    startTime: BigNumberish;
    duration: BigNumberish;
    initialized: boolean;
  };

  export type VestingScheduleStructOutput = [
    totalAmount: string,
    releasedAmount: string,
    startTime: bigint,
    duration: bigint,
    initialized: boolean
  ] & {
    totalAmount: string;
    releasedAmount: string;
    startTime: bigint;
    duration: bigint;
    initialized: boolean;
  };
}

export interface EntropyVestingWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateReleasable"
      | "confidentialProtocolId"
      | "createVestingWithEntropy"
      | "entropyOracle"
      | "getEntropyOracle"
      | "getVestingSchedule"
      | "release"
      | "requestVestingWithEntropy"
      | "vestingRequestCount"
      | "vestingRequests"
      | "vestingSchedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "VestingCreated"
      | "VestingReleased"
      | "VestingRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateReleasable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVestingWithEntropy",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestVestingWithEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vestingRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingSchedules",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateReleasable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVestingWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestVestingWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingSchedules",
    data: BytesLike
  ): Result;
}

export namespace VestingCreatedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    startTime: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    beneficiary: string,
    startTime: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    beneficiary: string;
    startTime: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingReleasedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    encryptedAmount: BytesLike
  ];
  export type OutputTuple = [beneficiary: string, encryptedAmount: string];
  export interface OutputObject {
    beneficiary: string;
    encryptedAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingRequestedEvent {
  export type InputTuple = [beneficiary: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [beneficiary: string, requestId: bigint];
  export interface OutputObject {
    beneficiary: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyVestingWallet extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyVestingWallet;
  waitForDeployment(): Promise<this>;

  interface: EntropyVestingWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateReleasable: TypedContractMethod<
    [beneficiary: AddressLike],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createVestingWithEntropy: TypedContractMethod<
    [
      beneficiary: AddressLike,
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getVestingSchedule: TypedContractMethod<
    [beneficiary: AddressLike],
    [EntropyVestingWallet.VestingScheduleStructOutput],
    "view"
  >;

  release: TypedContractMethod<
    [
      beneficiary: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  requestVestingWithEntropy: TypedContractMethod<
    [tag: BytesLike],
    [bigint],
    "payable"
  >;

  vestingRequestCount: TypedContractMethod<[], [bigint], "view">;

  vestingRequests: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  vestingSchedules: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        totalAmount: string;
        releasedAmount: string;
        startTime: bigint;
        duration: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateReleasable"
  ): TypedContractMethod<[beneficiary: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVestingWithEntropy"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getVestingSchedule"
  ): TypedContractMethod<
    [beneficiary: AddressLike],
    [EntropyVestingWallet.VestingScheduleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestVestingWithEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "vestingRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vestingRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vestingSchedules"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        totalAmount: string;
        releasedAmount: string;
        startTime: bigint;
        duration: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "VestingCreated"
  ): TypedContractEvent<
    VestingCreatedEvent.InputTuple,
    VestingCreatedEvent.OutputTuple,
    VestingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VestingReleased"
  ): TypedContractEvent<
    VestingReleasedEvent.InputTuple,
    VestingReleasedEvent.OutputTuple,
    VestingReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VestingRequested"
  ): TypedContractEvent<
    VestingRequestedEvent.InputTuple,
    VestingRequestedEvent.OutputTuple,
    VestingRequestedEvent.OutputObject
  >;

  filters: {
    "VestingCreated(address,uint64,uint64)": TypedContractEvent<
      VestingCreatedEvent.InputTuple,
      VestingCreatedEvent.OutputTuple,
      VestingCreatedEvent.OutputObject
    >;
    VestingCreated: TypedContractEvent<
      VestingCreatedEvent.InputTuple,
      VestingCreatedEvent.OutputTuple,
      VestingCreatedEvent.OutputObject
    >;

    "VestingReleased(address,bytes)": TypedContractEvent<
      VestingReleasedEvent.InputTuple,
      VestingReleasedEvent.OutputTuple,
      VestingReleasedEvent.OutputObject
    >;
    VestingReleased: TypedContractEvent<
      VestingReleasedEvent.InputTuple,
      VestingReleasedEvent.OutputTuple,
      VestingReleasedEvent.OutputObject
    >;

    "VestingRequested(address,uint256)": TypedContractEvent<
      VestingRequestedEvent.InputTuple,
      VestingRequestedEvent.OutputTuple,
      VestingRequestedEvent.OutputObject
    >;
    VestingRequested: TypedContractEvent<
      VestingRequestedEvent.InputTuple,
      VestingRequestedEvent.OutputTuple,
      VestingRequestedEvent.OutputObject
    >;
  };
}
